# Generated by Django 4.1.7 on 2023-03-27 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='user',
            name='token_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='토큰 업데이트 시간'),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', verbose_name='논문 PDF 요청 주소')),
                ('content', models.TextField(blank=True, verbose_name='논문 요약 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='요청자', on_delete=django.db.models.deletion.CASCADE, related_name='thesises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
